### PR TITLE
My captain hacks

### PR DESCRIPTION
**Pull request by mikehale**
Hi Matthew,
It's been over a months since I started playing with captain. Thanks for a gem of a gem BTW :)

I've hacked in numerous changes some of which may not be appropriate to keep in captain since the project description is to build cd images and not install that image. I'd love to hear your thoughts on what to do with the install bits.
- support for 1.9.2
- custom preeseed file location
- virtualbox support
- auto_install option to skip boot menu
- install cdimage and vboxadditions (maybe should be moved to another gem)

### CODE REVIEW

**Comment by matthewtodd** [comment]
Hey, Michael -- thank you!

I'm just getting back into the swing of things, now that our holiday visitors are on their way back to the States. I'll look through these changes and apply on Monday.

Cheers!  -- Matthew

**Comment by matthewtodd** [comment]
Hey, Michael!

I've cherry-picked your work into the 5 separate logical bits you mention, and have started to merge and push.

It's the end of the day here, so I'll start off tomorrow with 1.9.2 compatibility (thinking I'll have the .rvmrc explicitly say "1.9.2"), then look into preseed templating and virtual box. (Totally welcome the idea of virtual box, want to first understand what it means to install an image -- your comments welcome!)

Best,  -- Matthew

**Comment by mikehale** [comment]
So virtualbox and installing an image are definitely two separate concepts. Adding virtualbox support just means creating a virtualbox config, disk, and attaching the captain constructed ISO to it. The install side of things was strictly to allow me to build a vagrant box file with the vbox additions in it. I'm not sure that doing an install for the purpose of creating a vagrant box is inside the scope of what captain is supposed to be. I could potentially move that functionality out into my rake file. I suppose the other option would be to create a .deb for the vbox additions compiled against the kernel I am using and include that package as part of the ISO. Actually I should probably dig into https://github.com/jedi4ever/veewee more since it looks like it's goal in life is creating vagrant boxes.

**Comment by mikehale** [comment]
On a somewhat related note I've been meaning to dig into VMBuilder (https://launchpad.net/vmbuilder), which is the tool that Ubuntu uses internally for building the official Amazon EC2 Ubuntu images. Some things I really like about captain are:
- It is written in ruby
- I can script it from rake
- It minimizes network traffic and speeds ISO builds by caching packages locally.
- It just works on my mac

VMBuilder seems nice because it is the official ubuntu tool with community backing, but I don't think it would run on a mac ATM. Having to build an ISO in an ubuntu VM is kinda lame IMO.

**Comment by matthewtodd** [comment]
Ah-ha, have just read more carefully what's happening in `Captain::VM::VirtualBox#install` -- seems pretty convenient to me!

(I've been thinking captain's core value is in (cross-platform) understanding the structure of Debian repositories well enough to make interesting things from them (which, at the moment, is just installer ISOs, though I had also imagined pulling together a local package repository, kind of like apt-mirror). Indeed, that's why it's called cAPTain! The virtual machine stuff is there solely for convenience.)

You're helping me see that, someday, captain's VM stuff might be spun out or just plain whacked in favor of more focused gems, but for now I feel happy to merge in VirtualBox support. :-)

Also, cool, just read about VMBuilder -- the first advantage I notice over captain (other than having lots more eyes on it!) is that it skips the installer step. (But yes, agreed that it's not so fun to boot a VM to build an ISO.)

**Comment by mikehale** [comment]
The core value you have described (cross-platform understanding of Debian repositories) makes a lot of sense to me. Perhaps the project description should reflect that core value?

Thanks for pointing out that VMBuilder creates a vm disk image without having to do an install. It took a whole night of pondering and then when I woke up this morning it hit me that, VMBuilder just creates vm disk images without running the debian installer.

**Comment by matthewtodd** [comment]
Good call -- have just updated project documentation to reflect this core value.

So, now all that remains unmerged of this pull request is the ability to specify a custom preseed file. I'm considering a different approach and wondering about your thoughts:

Rather than specifying a new config option, how about allowing any of the templates to be overridden by placing a file of the same name under #{captain_directory}/templates? (Or something like it?)

Thanks for your help, Michael! This is fun.  -- M

**Comment by mikehale** [comment]
Convention over configuration, I like it.

**Comment by mikehale** [comment]
After digging through the VMBuilder source code, it looks to be installing into a chroot. Unfortunately for us it seems to be using a number of linux specific things to do the install. This seems like a major road block to being able to create an installed disk image from a non-linux platform... at least using the chroot approach.

**Comment by mikehale** [comment]
After digging through the VMBuilder source code, it looks to be installing into a chroot. Unfortunately for us it seems to be using a number of linux specific things to do the install. This seems like a major road block to being able to create an installed disk image from a non-linux platform... at least using the chroot approach.

**Pull request closed without merging**
